# Generated by Django 4.2 on 2024-05-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfortMLapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Shop',
        ),
    ]
