# Generated by Django 4.2 on 2024-05-30 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConfortMLapp', '0002_rename_produit_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('complet', models.BooleanField(default=False)),
                ('adresse_livraison', models.CharField(blank=True, max_length=255, null=True)),
                ('code_coupon', models.CharField(blank=True, max_length=50, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ConfortMLapp.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfortMLapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ConfortMLapp.commande')),
            ],
        ),
    ]
