# Generated by Django 4.2 on 2024-05-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfortMLapp', '0003_commande_panieritem_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='PanierItem',
        ),
    ]
