# Generated by Django 4.2 on 2024-06-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfortMLapp', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shop',
            name='quantity_minimale',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='shop',
            name='quantity_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
