# Generated by Django 4.2 on 2024-06-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfortMLapp', '0008_remove_shop_quantity_shop_quantity_minimale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='first_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_added_cart', to='ConfortMLapp.shop'),
        ),
    ]
