# Generated by Django 5.0.6 on 2024-06-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfortMLapp', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
