# Generated by Django 4.2 on 2024-06-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfortMLapp', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
