# Generated by Django 5.0.6 on 2024-06-23 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_embauche', models.DateField(default=django.utils.timezone.now)),
                ('poste', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatutEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('malade', 'Malade'), ('conge', 'Congé')], max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_du_personnel.employe')),
            ],
        ),
    ]
