# Generated by Django 5.0.6 on 2024-06-23 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_du_personnel', '0003_employe_est_paye_employe_salaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='est_paye',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='salaire',
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_paye', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_du_personnel.employe')),
            ],
        ),
    ]
